import type { Metadata } from "next";
import "./globals.css";
import localFont from '@next/font/local'
import { Navigation } from "@/components/ui/Navigation";
import { CookiesProvider } from 'next-client-cookies/server';

const ubuntuNerd = localFont({
    src: [
        {
            path: '../../public/fonts/UbuntuSansMonoNerdFont-Regular.ttf',
            weight: '400'
        },
        {
            path: '../../public/fonts/UbuntuSansMonoNerdFontMono-Bold.ttf',
            weight: '700'
        }
    ],
    variable: '--font-ubuntu-nerd'
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <CookiesProvider>
            <html lang="en">
                <body className={` ${ ubuntuNerd.className } h-screen text-xs`}>
                    <Navigation/>
                    <div className="overflow-scroll h-full pb-10">
                        {children}
                    </div>
                </body>
            </html>
        </CookiesProvider>
    );
}
